# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT btre.wsgi

beta_settings:
    cloud_sql_instances: survey-info-237814:asia-south1:django-data

runtime_config:
  python_version: 3
# [END runtime]
